### ISSUE TITLE
JOhm.save() error:  EXECABORT Transaction discarded because of previous errors

### ISSUE THREAD

**Issue by biagionicp** [agrison/johm#9]
Was just testing out JOhm for the first time with `JOhm.save()`:

```
public void doThis() {
        Item item = new Item(100);
        
        JOhm.save(item);
 }
```

When I got this exception:
*I'm pretty sure this is an issue with JOhm because I can save to the Redis database successfully using `Jedis.set()` and `Jedis.hmset()`
 ```
redis.clients.jedis.exceptions.JedisDataException: EXECABORT Transaction discarded because of previous errors.
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:142)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:239)
	at redis.clients.jedis.Transaction.exec(Transaction.java:38)
	at redis.clients.jedis.BinaryJedis.multi(BinaryJedis.java:1632)
	at redis.clients.johm.Nest.multi(Nest.java:117)
	at redis.clients.johm.JOhm.save(JOhm.java:321)
	at redis.clients.johm.JOhm.save(JOhm.java:224)
	at org.pollinator.DoClass.doThis(DoClass.java:66)
```

Here is the Item class:
*also a Hibernate model class
```
@Model
@Entity
@Table(name="item")
public class Poll implements Serializable{
    
    @redis.clients.johm.Id
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id")
    private long mId;

    public Item(){
    }

    public Item(long id){
        mId = id;
    }
}
```

After `doThis()` is called, the item's id is added to a set in the Redis database called `Item:all` before the exception is thrown, but that's all that is created -- I flushed the redis database before calling `doThis()`. Anyone ever experience a similar issue?

**Comment by agrison** [comment]
Hey @biagionicp, 

in your sample the Item class cannot be saved into redis as a model since it doesn't have any `@Attribute` field. 
Thus it leads to a call to `HMSET` in redis with an empty hash which is invalid since `HMSET` expect at least one entry (key + value). I think that the error has nothing to do with Hibernate nor the fact that your id field is named `mId`.

The id field is stored in the name of the key (`Item:1`) and not into the hash that's why the number of field for that hash is `0`.

However, I did read the following [Jedis issue](https://github.com/xetorthio/jedis/pull/498) while searching for your problem, and I may modify the way the id + del + hmset is being done almost transactionnaly in the `save` method.

But please first retry by adding an additional field to your `Item` example.

**Comment by biagionicp** [comment]
Also, it's hard for me to debug this issue, being that there is no source jar offered so all the line numbers in the stacktrace point to the line numbers of bytecode statements in the compiled java class.

**Comment by biagionicp** [comment]
Will do
*closed the issue on accident

**Comment by biagionicp** [comment]
works like a charm. thanks for the help!

**Comment by agrison** [comment]
Good to know, have fun!
